<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Add Product</title>
<style>
    body {font-family: Arial, Helvetica, sans-serif;}
    * {box-sizing: border-box;}

    input[type=text], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    margin-top: 6px;
    margin-bottom: 16px;
    resize: vertical;
    }

    input[type=submit] {
    background-color: #04AA6D;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    }

    input[type=submit]:hover {
    background-color: #45a049;
    }

    .container {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
    }
</style>
</head>
<body>

<h3>Add Product Form</h3>
<div class="container">
  <form action="/ecommerce/create_product" method="post">
    <input type="hidden" id="pid" name="productData[id]" value="<?php echo $product->id ?? ''; ?>">
    <label for="pname">Product Name</label>
    <input required type="text" id="pname" name="productData[name]" value="<?php echo $product->name ?? ''; ?>" placeholder="Your Product name..">

    <label for="pprice">Product price</label>
    <input required type="text" id="pprice" name="productData[price]" value="<?php echo $product->price ?? ''; ?>" placeholder="Your Product price..">

    <label for="pcategory">Product category</label>
    <input required type="text" id="pcategory" name="productData[category]" value="<?php echo $product->category ?? ''; ?>" placeholder="Your Product category..">

    <label for="ptag">Product stock</label>
    <input required type="text" id="ptag" name="productData[stock]" value="<?php echo $product->stock ?? ''; ?>" placeholder="Your Product stock..">

    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
        <button type="button" onClick = 'addNewMeta()'>Add New meta</button>
        <button type="button" onClick = 'addNewVariation()'>Add New Variation</button>
        <table id="metaTable">
            <tr>
                <th>Meta Key</th>
                <th>Meta Value</th>
                <th>Meta Delete</th>
            </tr>
            <tr>
                <td><input type="text" name="productData[meta][meta_key][]"></td>
                <td><input type="text" name="productData[meta][meta_value][]"></td>
            </tr>
        </table>
        <table id="variationTable">
            <tr>
                <th>Variation name</th>
                <th>Variation price</th>
                <th>Variation description</th>
                <th>Delete Variation</th>
            </tr>
            <tr>
                <td><input type="text" name="productData[variation][variation_name][]"></td>
                <td><input type="text" name="productData[variation][variation_price][]"></td>
                <td><input type="text" name="productData[variation][variation_desc][]"></td>
            </tr>
        </table>
        <br>
    <input type="submit" value="Submit">
  </form>
</div>
</html>
<script>
    function addNewMeta() {
        var x = document.getElementById('metaTable').insertRow(-1);
        var y = x.insertCell(0);
        var z = x.insertCell(1);
        var x = x.insertCell(2);
        y.innerHTML= '<input type="text" name="productData[meta][meta_key][]">';
        z.innerHTML= '<input type="text" name="productData[meta][meta_value][]">';
        x.innerHTML= '<td><a href="javascript:void(0);" onClick = "deleteMeta( this.parentElement.parentElement )" class="action-delete"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">\
        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>\
        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>\
        </svg></a></td>';
    }

    function addNewVariation() {
        var x = document.getElementById('variationTable').insertRow(-1);
        var vn = x.insertCell(0);
        var vp = x.insertCell(1);
        var vd = x.insertCell(2);
        var vdl = x.insertCell(3);
        vn.innerHTML  = '<td><input type="text" name="productData[variation][variation_name][]"></td>';
        vp.innerHTML  = '<td><input type="text" name="productData[variation][variation_price][]"></td>';
        vd.innerHTML  = '<td><input type="text" name="productData[variation][variation_desc][]"></td>';
        vdl.innerHTML = '<td><a href="javascript:void(0);" onClick = "deleteMeta( this.parentElement.parentElement )" class="action-delete"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">\
        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>\
        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>\
        </svg></a></td>';
    }

    const deleteMeta = ( row ) => {
        row.remove();
    }
</script>