<html>
    <head>
        <title>Weather Forecast</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    </head>
    <body>
        <form method="POST" novalidate>
            <div class="col-md-4">
                <label for="validationCountry" class="form-label">Username</label>
                <div class="input-group has-validation">
                    <span class="input-group-text" id="inputGroupPrepend">Search</span>
                    <input type="text" class="form-control" name="q" id="validationCountry" value="<?php echo $input ?? ''; ?>" required>
                    <button class="btn btn-primary" type="submit">Submit form</button>
                </div>
            </div>
        </form>
        <?php if( ! empty( $report ) ) : ?>

            <?php
            $location = $report['location'] ?? array();
            $current  = $report['current'] ?? array();
            ?>

            <div class="container px-1 px-sm-4 py-5 mx-auto">
                <div class="row d-flex justify-content-center">
                    <div class="card text-center pt-4 border-0">
                    <h4 class="mb-0"><?php echo $location['country'] ?? ''; ?></h4>
                    <small class="text-muted mb-3"><?php echo $location['name'] ?? ''; ?>(<?php echo $location['tz_id'] ?? ''; ?>)</small>
                    <small class="text-muted mb-3"><?php echo $location['localtime'] ?? ''; ?></small>
                    <h2 class="large-font"><?php echo $current['temp_c']; ?>&#176;C</h2>
                    <div class="text-center mt-3 mb-4">
                        <img class="city-symbol" src="https://i.imgur.com/QA63I0q.png">
                    </div>
                    <div class="row d-flex px-3 mt-auto">
                        <div class="d-flex flex-column block first-block">
                            <small class="text-muted mb-0">Wind MPH</small>
                            <div class="text-center"></div>
                            <h6><strong><?php echo $current['wind_mph']; ?>&#176;</strong></h6>
                        </div>
                        <div class="d-flex flex-column block active">
                            <small class="text-muted mb-0">Degree</small>
                            <div class="text-center"></div>
                            <h6><strong><?php echo $current['wind_dir']; ?></strong></h6>
                        </div>
                        <div class="d-flex flex-column block">
                            <small class="text-muted mb-0">Cloud</small>
                            <div class="text-center"></div>
                            <h6><strong><?php echo $current['cloud']; ?>&#176;</strong></h6>
                        </div>
                        <div class="d-flex flex-column block active">
                            <small class="text-muted mb-0">UV</small>
                            <div class="text-center"></div>
                            <h6><strong><?php echo $current['uv']; ?>&#176;</strong></h6>
                        </div>
                        <div class="d-flex flex-column block last-block">
                            <small class="text-muted mb-0">Pressure</small>
                            <div class="text-center"></div>
                            <h6><strong><?php echo $current['pressure_mb']; ?>&#176;</strong></h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php endif; ?>
    </body>

    <?php if ( ! empty( $err ) ) : ?>
        <script>
            Swal.fire({
                title: 'Error!',
                text: '<?php echo $err; ?>',
                icon: 'error',
                confirmButtonText: 'Cool'
            });
        </script>    
    <?php endif; ?>
    <footer>
        <style>
            .px-3 {
                padding-right: 1rem!important;
                padding-left: 1rem!important;
                padding-bottom: 1rem !important;
            }
            body {
                color: #7B1FA2;
                overflow-x: hidden;
                height: 100%;
                background-color: #6A1B9A;
                background-repeat: no-repeat;
            }
            .card {
                width: 400px;
                background-color: #F3E5F5;
            }
            .btn-primary {
                color: #fff;
                background-color: #f7e1f65e;
                border-color: #f7e1f65e;
            }
        
            .block {
                width: 20%;
                background-color: #E1BEE7;
                cursor: pointer;
                padding: 10px 0px;
            }
        
            .first-block {
                border-bottom-left-radius: 5px;
            }
        
            .last-block {
                border-bottom-right-radius: 5px;
            }
        
            .block.active, .block:hover {
                background-color: #CE93D8;
            }
        
            .city-symbol {
                width: 200px;
                height: 250px;
            }
        
            .large-font {
                font-size: 60px;
            }
        
            .symbol-img {
                width: 40px;
                height: 40px;
            }
        
            @media screen and (max-width: 400px) {
                .card {
                    width: 92%;
                }
            }   
        </style>
    </footer>
</html>