<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>Order List</title>
    <style>
        .normal_wrapper::-webkit-scrollbar {
            width:5px;
            height: 5px;
            background-color: #007aff22;
        }

        .normal_wrapper::-webkit-scrollbar-thumb {
            background-color: #007aff;
        }

        td::selection {
            color: #007aff;
            background: transparent;
            text-align :center;
        }

        td, th {
            min-width: 100px;
            padding: 5px;
            text-align :center;
        }

        tr:nth-of-type(even) {
            background-color: #f5f5f5;
        }

        thead, tfoot {
            background-color: #007aff;
        }

        thead th, tfoot th {
            color: #ffffff;
        }

        .normal_wrapper {
            max-height: 400px;
            overflow-y: auto;
            box-shadow: 0 -10px 27px -25px black inset;
        }     
        .button {
            background-color: #ffffff; /* Green */
            border: 4px solid #4CAF50;
            color: #4CAF50;
            padding: 15px 32px;
            margin-bottom:12px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
        }
        .button:hover {
            background-color: #4CAF50; /* Green */
            color: white;
        }
    </style>
</head>
<body>
    <a class="button" href="/add-order">Add New</a>
    <table id="example" class="display nowrap" style="width:100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Customer Name</th>
                <th>Customer Address</th>
                <th>Customer Zipcode</th>
                <th>Line Items</th>
                <th>Edit</th>
                <th>Cancel</th>
            </tr>
        </thead>
        <tbody>
            <?php if( empty( count( $orders ) ) ) : ?>
                <tr>
                    <td colspan="7">No orders found</td>
                </tr>
                <?php else: ?>
                    <?php foreach ( $orders as $key => $order ) : ?>
                        <tr>
                            <td>#<?php echo ( $order->id ); ?></td>
                            <td><?php echo ( $order->cust_name ); ?></td>
                            <td>$<?php echo ( $order->cust_addr ); ?></td>
                            <td><?php echo ( $order->zipcode ); ?></td>
                            <td><?php echo ( $order->line_items ); ?></td>
                            <td><?php echo ( $order->status ); ?></td>
                            <th><a href="/add-order/?pid=<?php echo $order->id; ?>"><i class="material-icons" style="font-size:28px;color:green">edit</i></a></th>
                            <th><a href="/order-list/delete/?pid=<?php echo $order->id; ?>"><i class="material-icons" style="font-size:28px;color:red">delete</i></a></th>
                        </tr>
                    <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
        <tfoot>
            <tr>
                <th>ID</th>
                <th>Customer Name</th>
                <th>Customer Address</th>
                <th>Customer Zipcode</th>
                <th>Line Items</th>
                <th>Edit</th>
                <th>Cancel</th>
            </tr>
        </tfoot>
    </table>
</body>
</html>