
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--  This file has been downloaded from bootdey.com @bootdey on twitter -->
    <!--  All snippets are MIT license http://bootdey.com/license -->
    <title>Settings page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="container-xl px-4 mt-4">
        <div class="row">
            <div class="col-xl-8">
                <!-- Account details card-->
                <div class="card mb-4">
                    <div class="card-header">Settings</div>
                    <div class="card-body">
                        <form action="/settings/validate" method="post">
                            <!-- Form Group (username)-->
                            <div class="mb-3">
                                <label class="small mb-1" for="inputTitle">Title Optimization</label>
                                <select class="form-control" id="inputTitle" name="settingsData[title]">
                                    <option value="">Choose an option</option>
                                    <option value="with_tags">With Tags</option>
                                    <option value="without_tags">Without Tags</option>
                                </select>
                            </div>
                            <!-- Form Row-->
                            <div class="row gx-3 mb-3">
                                <div class="col-md-6">
                                    <label class="small mb-1" for="inputPrice">Default Price</label>
                                    <input class="form-control" name="settingsData[price]" id="inputPrice" type="text" placeholder="Enter Default Price" value="">
                                </div>
                                <div class="col-md-6">
                                    <label class="small mb-1" for="inputStock">Default Stock</label>
                                    <input class="form-control" name="settingsData[stock]" id="inputStock" type="text" placeholder="Enter Default Stock" value="">
                                </div>
                            </div>
                            <div class="row gx-3 mb-3">
                                <div class="col-md-6">
                                    <label class="small mb-1" for="inputZipcode">Default Zipcode</label>
                                    <input class="form-control" name="settingsData[zipcode]" id="inputZipcode" type="text" placeholder="Enter Default Zipcode" value="">
                                </div>
                            </div>
                            <!-- Save changes button-->
                            <button class="btn btn-primary" type="submit">Save changes</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <style type="text/css">
        body{
            margin-top:20px;
            background-color:#f2f6fc;
            color:#69707a;
        }
        .form-control {
            display: block;
            width: 100%;
            padding: 0.875rem 1.125rem;
            font-size: 0.875rem;
            font-weight: 400;
            line-height: 1;
            color: #69707a;
            background-color: #fff;
            background-clip: padding-box;
            border: 1px solid #c5ccd6;
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
            border-radius: 0.35rem;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }
    </style>
</body>
</html>