<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Table</title>
    <style>
        .normal_wrapper::-webkit-scrollbar {
            width:5px;
            height: 5px;
            background-color: #007aff22;
        }

        .normal_wrapper::-webkit-scrollbar-thumb {
            background-color: #007aff;
        }

        td::selection {
            color: #007aff;
            background: transparent;
            text-align :center;
        }

        td, th {
            min-width: 100px;
            padding: 5px;
            text-align :center;
        }

        tr:nth-of-type(even) {
            background-color: #f5f5f5;
        }

        thead, tfoot {
            background-color: #007aff;
        }

        thead th, tfoot th {
            color: #ffffff;
        }

        .normal_wrapper {
            max-height: 400px;
            overflow-y: auto;
            box-shadow: 0 -10px 27px -25px black inset;
        }     
        .button {
            background-color: #ffffff; /* Green */
            border: 4px solid #4CAF50;
            color: #4CAF50;
            padding: 15px 32px;
            margin-bottom:12px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
        }
        .button:hover {
            background-color: #4CAF50; /* Green */
            color: white;
        }
    </style>
</head>
<body>
    <a class="button" href="/add-product">Add New</a>
    <table id="example" class="display nowrap" style="width:100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Price</th>
                <th>Description</th>
                <th>Tags</th>
                <th>Stock</th>
            </tr>
        </thead>
        <tbody>
            <?php if( empty( $products ) ) : ?>
                <tr>
                    <td colspan="5">No products found</td>
                </tr>
                <?php else: ?>
                    <?php foreach ( $products as $key => $product ) : ?>
                        <tr>
                            <td>#<?php echo ( $product->id ); ?></td>
                            <td><?php echo ( $product->name ); ?></td>
                            <td>$<?php echo ( $product->price ); ?></td>
                            <td><?php echo ( $product->description ); ?></td>
                            <td><?php echo ( $product->tag ); ?></td>
                            <td><?php echo ( $product->stock ); ?></td>
                        </tr>
                    <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
        <tfoot>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Price</th>
                <th>Description</th>
                <th>Tags</th>
                <th>Stock</th>
            </tr>
        </tfoot>
    </table>
</body>
</html>