<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #04AA6D;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
</head>
<body>

<h3>Add Order Form</h3>

<div class="container">
  <form action="/validate">
    <label for="pname">Order Name</label>
    <input type="text" id="pname" name="Ordername" placeholder="Your Order name..">

    <label for="pprice">Order price</label>
    <input type="text" id="pprice" name="pricename" placeholder="Your Order price..">

    <label for="ptag">Order tag</label>
    <input type="text" id="ptag" name="tagname" placeholder="Your Order tag..">

    <label for="ptag">Order stock</label>
    <input type="text" id="ptag" name="tagname" placeholder="Your Order stock..">

    <label for="pprice">Order price</label>
    <input type="text" id="pprice" name="pricename" placeholder="Your Order price..">

    <label for="description">Order Description</label>
    <textarea id="description" name="description" placeholder="Write something.." style="height:200px"></textarea>
    <input type="submit" value="Submit">
  </form>
</div>

</body>
</html>
