<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

input[type=text],input[type=number], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #04AA6D;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
</head>
<body>

<h3>Add Order Form</h3>
<div class="container">
  <form method="post" action="/add-order/validate">

    <label for="cust_name">Customer Name</label>
    <input type="text" id="cust_name" name="orderData[cust_name]" placeholder="Your Customer name..">

    <label for="cust_addr">Customer Address</label>
    <textarea id="cust_addr" name="orderData[cust_addr]" placeholder="Your Customer Address..." style="height:75px"></textarea>

    <label for="cust_zipcode">Customer Zipcode</label>
    <input type="text" id="cust_zipcode" name="orderData[cust_zipcode]" placeholder="Your Customer Zipcode..">

    <label for="order_status">Order status</label>
    <select id="order_status" name="orderData[order_status]" id="order_status">
      <option value="">Select a status</option>
      <option value="pending">Pending</option>
      <option value="processing">Processing</option>
      <option value="completed">Completed</option>
      <option value="refunded">Refunded</option>
      <option value="cancelled">Cancelled</option>
    </select>
    <?php if ( ! empty( count( $products ) ) ) : ?>
      <?php for ($i=1; $i <= count( $products ); $i++) : ?>
        <label for="line_items">Order Line Items <?php echo $i;?></label>
        <select name="orderData[line_items][id][<?php echo $i;?>]" id="line_items">
          <option value="">Select a product</option>
          <?php foreach ( $products as $key => $product ) : ?>
            <option value="<?php echo $product->id; ?>"><?php echo $product->name; ?></option>
          <?php endforeach; ?>
        <select>
        <input type="number" id="line_item_quantity" name="orderData[line_items][quantity][<?php echo $i;?>]" placeholder="Quantity..">
      <?php endfor; ?>
    <?php endif; ?>
  <input type="submit" value="Submit">
  </form>
</div>

</body>
</html>
