<html>
    <head>
        <title>
            Welcome to Shop
        </title>
    </head>
    <body>
    <table id="products" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Category</th>
                <th>Price</th>
                <th>Stock</th>
                <th>Meta</th>
                <th>Variations</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Category</th>
                <th>Price</th>
                <th>Stock</th>
                <th>Meta</th>
                <th>Variations</th>
            </tr>
        </tfoot>
        <tbody>
        </tbody>
    </table>
    <div>
        <a href="/ecommerce/create_product" class="button">Add New Product</a>
    </div>
    </body>
    <footer>
        <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
        <style>
            body {
                margin: 2rem;
            }
            table, thead, tfoot {
                margin: 2rem;
                text-align:center;
            }
            .paginate_button {
                border-radius: 0 !important;
            }
            a.button {
                color: #000000;
                border: 2px solid #000000;
                border-radius: 6px;
                padding: 5px 40px;
                text-decoration : none;
                background: #0f0f0f33;
            }
            :root {
                --hue: 223;
                --bg: hsl(var(--hue),10%,90%);
                --fg: hsl(var(--hue),10%,10%);
                --primary: hsl(var(--hue),90%,55%);
                --trans-dur: 0.3s;
                font-size: calc(16px + (20 - 16) * (100vw - 320px) / (1280 - 320));
            }
            body {
                background-color: var(--bg);
                color: var(--fg);
                font: 1em/1.5 "DM Sans", sans-serif;
                place-items: center;
                transition:
                    background-color var(--trans-dur),
                    color var(--trans-dur);
            }
        </style>
        <script>
            jQuery(document).ready(function($) {
                var table = $('#products').DataTable({ 
                    ajax: 'products',
                    columns: [
                        { data: 'id' },
                        { data: 'name' },
                        { data: 'category' },
                        { data: 'price' },
                        { data: 'stock' },
                        { data: 'meta' },
                        { data: 'variations' },
                    ],
                });
            });
        </script>
    </footer>
</html>